### ISSUE TITLE
特征工程中，箱型图不一致

### ISSUE THREAD

**Issue by lx12633036** [datawhalechina/team-learning-data-mining#1]
您好，我前面两个小节和您的图出来是一致的，但在特征工程中箱型图和您完全不一样。
即使是使用您的代码，配合这份数据 依然结果不一致。请问您在特征工程前对数据进行了什么处理吗？
![image](https://user-images.githubusercontent.com/40138154/91657876-5c9f8000-eaf7-11ea-8295-b17e27f259db.png)

**Comment by Sm1les** [comment]
已私聊解答

**Comment by banjamin555** [comment]
#include <iostream>
#include <vector>
using namespace std;
int main() {
    int n, k;
    cin >> n >> k;
    vector<int> price(n, 0);
    for(int i = 0; i < n; ++i) {
        cin >> price[i];
    }
    vector<int> dp(k + 1, 0);
    for(int i = 0; i < n; ++i) {
        for(int j = k; j >= price[i]; --j) {
            dp[j] = max(dp[j], dp[j - price[i]] + 1);
        }
    }
    cout << dp[k] << endl;
    return 0;
}



在 2020-09-18 20:32:25，":)s" <notifications@github.com> 写道：

已私聊解答
