### ISSUE TITLE
‘对象类型特征转换到数值’ 段落 转换前后 数值不一致

### ISSUE THREAD

**Issue by XueKX** [datawhalechina/team-learning-data-mining#2]
data_train['employmentLength'].value_counts(dropna=False).sort_index()

**Comment by XueKX** [comment]
![image](https://user-images.githubusercontent.com/25972966/93561948-a7563e80-f9b7-11ea-8115-7e172193b803.png)

**Comment by panda-puff** [comment]
> data_train['employmentLength'].value_counts(dropna=False).sort_index()

我也发现这个事情啦，其实代码没有问题。只不过data_train['employmentLength'].value_counts(dropna=False).sort_index()出来的值是data_train的，而把年份转换后，再打印出来的值，是data的，而执行完for后，data对应的是data_test，所以会前后不一致。
这是我个人的理解，我不是作者哈，希望可以帮到你，如果理解有误希望帮忙指正
